# Generated by Django 5.1.4 on 2026-06-17 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='realtime', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('publish', 'Publish event'), ('comment', 'New comment'), ('comment_approved', 'Comment approved'), ('milestone', 'Milestone'), ('subscriber', 'New subscriber')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='blog_activi_user_id_02302f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post', 'created_at'], name='blog_postvi_post_id_2e6acd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('post.published', 'Post published'), ('comment.created', 'Comment created'), ('user.subscribed', 'User subscribed')], max_length=40)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('health', models.CharField(choices=[('awaiting', 'Awaiting first delivery'), ('functional', 'Functional'), ('failing', 'Failing')], default='awaiting', max_length=20)),
                ('last_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'event', 'is_active'], name='blog_webhoo_owner_i_40f3dd_idx')],
            },
        ),
    ]
